version: '3.8'

services:
  eskomsepushnotifier:
    image: eskomsepushnotifier:latest
    container_name: eskomsepushnotifier
    ports:
      - 9000:9000
    command: npm run prod
    env_file: ./.env
    environment: 
      - TZ=Africa/Johannesburg
    volumes:
    - ./config.ts:/config.ts

